# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Title Rcpp function
#'
#' @export
try_rcpp <- function(x) {
    .Call(`_GDFMM_try_rcpp`, x)
}

example_GDFMM_sampler_c <- function(data, P0_prior_name) {
    .Call(`_GDFMM_example_GDFMM_sampler_c`, data, P0_prior_name)
}

#' Eigen library usage example
#'
#' @export
EigenTest <- function() {
    invisible(.Call(`_GDFMM_EigenTest`))
}

#' Testing GSL wrappers
#'
#' @export
TestGSL <- function() {
    invisible(.Call(`_GDFMM_TestGSL`))
}

