# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Title Rcpp test function
#'
#' @export
try_Rcpp <- function(x) {
    .Call(`_GDFMM_try_Rcpp`, x)
}

